import Head from 'next/head'
import { useRouter } from 'next/router'
import { ProductDetails } from 'components/product-details'

export default function ProductDetailsPage() {
  const router = useRouter()

  return (
    <>
      <Head>
        <title>Next E-commerce Product Details</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ProductDetails id={router.query.id} />
    </>
  )
}
