import Head from 'next/head'
import { Main } from 'components/main'
import { dehydrate, QueryClient } from '@tanstack/react-query'
import { getProducts } from 'api/products'

export default function HomePage() {
  return (
    <>
      <Head>
        <title>Next E-commerce Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main />
    </>
  )
}

export async function getServerSideProps() {
  const queryClient = new QueryClient()

  await queryClient.prefetchQuery(['products'], getProducts)

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  }
}
